### ISSUE TITLE
Implementation bug in A* algorithm

### ISSUE THREAD

**Issue by wahllca** [KIT-MRT/behavior_generation_lecture_python#3]
https://github.com/KIT-MRT/behavior_generation_lecture_python/blob/53279f0e3ae82caeb464d09db63974de67609be1/src/graph_search/a_star.py#L134

I'm not sure if I'm misunderstanding the algorithm, but i think the if condition should check if the node _x_tilde_ is already in the open set or if the current calculated _cost to come_ of this node is smaller than the _cost to come_ calculated in a previous step.
Right now, the if condition checks if the current _cost to come_ is smaller than the approximated  _cost to go_.
`
if (
                            not x_tilde.node in [x.node for x in open_set]
                            or cost < x_tilde.G
                        ):
`
I think the code should look like this, replacing _x_tilde.G_ with _x_tilde.C_:
`
if (
                            not x_tilde.node in [x.node for x in open_set]
                            or cost < x_tilde.C
                        ):
`

**Comment by m-naumann** [comment]
Thanks for reporting @wahllca! We are looking into refactoring this implementation.
